version: '3.10'
services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - './api:/app:cached'
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
